version: '3'
services:
  job-service:
    image: rangeldiego/job-service
    container_name: 'job-service'
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:postgresql://postgres-job:5432/job-service
      SPRING.DATASOURCE.USERNAME: postgres
      SPRING.DATASOURCE.PASSWORD: postgres
    networks:
      - api-job
    ports:
      - 8889:8889
      - 5007:5007
#    extra_hosts:
#      - "dockerhost:$DOCKERHOST"

  postgres-job:
    image: postgres:9.6
    container_name: postgres-job
    hostname: postgres
    environment:
      POSTGRES_DB: "cardsapi"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      TZ: "GMT"
    volumes:
      - ./docker/postgres/cardsapi:/var/lib/postgresql/data
    networks:
      - api-job
    ports:
      - "5433:5432"

networks:
  api-job:
    driver: bridge