version: '3'
services:
  job-service:
    image: rangeldiego/job-service
    container_name: 'job-service'
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
#      EUREKA.CLIENTE.SERVICEURL.DEFAULTZONE: http://naming-service:8761/eureka
#      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
#      RABBIT_URI: anqp://guest:guest@rabbit-mq:5672
#      SPRING_RABBITMQ_HOST: rabbit-mq
#      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      SPRING.DATASOURCE.URL: jdbc:postgresql://postgres-job:5432/job-service
      SPRING.DATASOURCE.USERNAME: postgres
      SPRING.DATASOURCE.PASSWORD: postgres
    networks:
      - api
    ports:
      - "8100:8100"

  postgres-job:
    image: postgres:9.6
    container_name: postgres-job
    hostname: postgres
    environment:
      POSTGRES_DB: "cardsapi"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      TZ: "GMT"
    volumes:
      - ./docker/postgres/cardsapi:/var/lib/postgresql/data
    networks:
      - api
    ports:
      - "5433:5432"

networks:
  api:
    driver: bridge