server:
  port: 8806

spring:
  application:
    name: job-service
  datasource:
    url: jdbc:postgresql://localhost:5433/job-service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    username: diegorangeljpa@gmail.com
    password: 123456
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          quitwait: false


#spring:
#  application:
#    name: job-service
#
#  datasource:
#    name: cardsprivate
#    driverClassName: oracle.jdbc.driver.OracleDriver
#    jdbcUrl: jdbc:oracle:thin:@localhost:1521:ORCLCDB
#    username: bandeira
#    password: bandeira
#    minimum-idle: 5
#    maximum-pool-size: 15
#    login-timeout: 10000
#    idle-timeout: 10000
#    connection-timeout: 10000
#    auto-commit: false
#    initialization-fail-fast: false
#    pool-name: HikariPool-avenida
#  jpa:
#    database: ORACLE
#    database-platform: org.hibernate.dialect.Oracle10gDialect
#    show_sql: true
#    generate-ddl: false
#    properties:
#      hibernate.hbm2ddl.auto: none
