server:
  port: 8888

  #brain.connect@dock.tech

spring:
  application:
    name: job-service
  datasource:
    url: jdbc:postgresql://localhost:5433/job-service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    username: monitoriabrain@gmail.com
    password: ftqbtoxmemfqrqdm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          quitwait: false
